In [6]:
import pandas as pd
import json
import requests
from xml.etree import ElementTree

In [8]:
r = requests.get('http://127.0.0.1:5000/station/6/registration?type=xml')
r.raw.decode_content = True

events = ElementTree.iterparse(r.raw)
for event, elem in events:
    print(event, elem)

ParseError: no element found: line 1, column 0 (<string>)

In [11]:
df = pd.read_excel('stations.xlsx')
df.head()

            StationName  Latitude  Longitude  Height  RegionId  OrganizationId
0        Мурманск город      69.0       33.1      51         2               1
1     Архангельск город      64.4       40.7       8         3               1
2         Магадан город      59.6      150.8     116         4               1
3   Санкт-Петербург ИЦП      60.0       30.3       6         5               1
4  Нижний Новгород Мыза      56.3       44.0     157         6               1

In [13]:
df.to_json('stations.json', orient='records', force_ascii=False)

In [3]:
organizations = [
    {
        "OrganizationName" : "Центральное управление по гидрометеорологии и мониторингу окружающей среды",
        "Address": "ул. Образцова, д.6",
        "WebSite": "http://www.ecomos.ru/",
        "ParentOrganizationId": None,
        "LocalityId": 1
    },
    {
        "OrganizationName" : "Владимирский центр по гидрометеорологии и мониторингу окружающей среды",
        "Address": "ул. Стрелецкая, д. 20",
        "WebSite": None,
        "ParentOrganizationId": 1,
        "LocalityId": 2
    },
    {
        "OrganizationName" : "Рязанский центр по гидрометеорологии и мониторингу окружающей среды",
        "Address": " ул. Почтовая, д. 50, корп. 1",
        "WebSite": "http://meteo62.ru",
        "ParentOrganizationId": 1,
        "LocalityId": 2
    }
]

with open('organizations.json', 'w') as wr:
    json.dump(organizations, wr, indent=4, ensure_ascii=False)

In [14]:
countries = [
    {
        "CountryName": "Россия",
        "LandArea": 16377742,
        "WaterArea": 720500
    },
    {
        "CountryName": "Канада",
        "LandArea": 9093507,
        "WaterArea": 891163
    },
        {
        "CountryName": "Китай",
        "LandArea": 9326410,
        "WaterArea": 270550
    },
        {
        "CountryName": "США",
        "LandArea": 9147593,
        "WaterArea": 377424
    }
]

with open('countries.json', 'w') as wr:
    json.dump(countries, wr, indent=4, ensure_ascii=False)

In [6]:
russia_regions = [
    {
        "RegionName": "Москва и московская область"
    },
    {
        "RegionName": "Мурманская область"
    },
    {
        "RegionName": "Архангельская область"
    },
    {
        "RegionName": "Магаданская область"
    },
    {
        "RegionName": "Ленинградская область"
    },
    {
        "RegionName": "Нижегородская область"
    },
    {
        "RegionName": "Республика Татарстан"
    },
    {
        "RegionName": "Пензенская область"
    },
    {
        "RegionName": "Свердловская область"
    },
    {
        "RegionName": "Омская область"
    },
    {
        "RegionName": "Республика Башкортостан"
    },
    {
        "RegionName": "Самарская область"
    },
    {
        "RegionName": "Иркутская область"
    },
    {
        "RegionName": "Забайкальский край"
    },
    {
        "RegionName": "Хабаровский край"
    },
    {
        "RegionName": "Камчатский край"
    },
    {
        "RegionName": "Республика Крым"
    },
    {
        "RegionName": "Краснодарский край"
    }
]

with open('russia_regions.json', 'w') as wr:
    json.dump(russia_regions, wr, indent=4, ensure_ascii=False)

In [2]:
canada_regions = [
    {
        "RegionName": "Альберта"
    },
    {
        "RegionName": "Британская Колумбия"
    },
    {
        "RegionName": "Квебек"
    },
    {
        "RegionName": "Остров Принца Эдуарда"
    },
    {
        "RegionName": "Саскачеван"
    }
]

with open('canada_regions.json', 'w') as wr:
    json.dump(canada_regions, wr, indent=4, ensure_ascii=False)

In [3]:
china_regions = [
    {
        "RegionName": "Гуйчжоу"
    },
    {
        "RegionName": "Шэньси"
    },
    {
        "RegionName": "Хубэй"
    }
]

with open('china_regions.json', 'w') as wr:
    json.dump(china_regions, wr, indent=4, ensure_ascii=False)

In [5]:
usa_regions = [
    {
        "RegionName": "Айдахо"
    },
    {
         "RegionName": "Аризона"
    },
    {
        "RegionName": "Калифорния"
    }
]

with open('usa_regions.json', 'w') as wr:
    json.dump(usa_regions, wr, indent=4, ensure_ascii=False)

In [15]:
russia_locality = [
    {
        "LocalityName": "Москва"
    },
    {
        "LocalityName": "Владимир"
    },
    {
        "LocalityName": "Рязань"
    }
]

with open('russia_locality.json', 'w') as wr:
    json.dump(russia_locality, wr, indent=4, ensure_ascii=False)

In [ ]:
canada_locality = [
    
]

with open('canada_locality.json', 'w') as wr:
    json.dump(russia_locality, wr, indent=4, ensure_ascii=False)

In [ ]:
china_locality = [
    
]

with open('china_locality.json', 'w') as wr:
    json.dump(russia_locality, wr, indent=4, ensure_ascii=False)

In [ ]:
usa_locality = [
    
]

with open('usa_locality.json', 'w') as wr:
    json.dump(russia_locality, wr, indent=4, ensure_ascii=False)

In [8]:
df = pd.read_json('Stations.json', encoding='1251')

In [11]:
df.head()

   WMOIndex           StationName  Latitude  Longitude  Height
0     22113        Мурманск город      69.0       33.1      51
1     22550     Архангельск город      64.4       40.7       8
2     25913         Магадан город      59.6      150.8     116
3     26063   Санкт-Петербург ИЦП      60.0       30.3       6
4     27459  Нижний Новгород Мыза      56.3       44.0     157

In [12]:
df.to_excel('stations.xlsx', index=False, columns=['StationName', 'Latitude', 'Longitude', 'Height'])

In [3]:
json.dump?